### ISSUE TITLE
[Bug] Auto Completion not working

### ISSUE THREAD

**Issue by icpryde** [nfm886/skin.cosmic#10]
I noticed when I go to type something with other skins like Resurrection it allows me to see suggestions for what I'm typing to auto complete.

No matter what I type with Cosmic it won't populate any suggestions for writing.

![Screen Shot 2021-08-11 at 4 17 24 PM](https://user-images.githubusercontent.com/29389746/129100050-97c0b79f-2258-415f-9b13-b4c3dcd2a8cb.png)

It should look like this as seen on resurrection:

![Screen Shot 2021-08-11 at 4 42 41 PM](https://user-images.githubusercontent.com/29389746/129100450-3f2abd30-a1a9-490c-bcaf-fba832bfa8f5.png)

**Comment by nfm886** [comment]
I removed that feature since it was not working on all devices. On some devices it caused Kodi to crash. It was real problem on systems like CoreELEC. I don't know if I want to bring back that feature. If so, it will be disabled by default.

**Comment by icpryde** [comment]
@nfm886 oh I see, I’ve used it in MacOS, windows, Nvidia shield and MiBox with no problems but I install this version of auto complete is where I’ve had the lost success.

https://github.com/icpryde/plugin.program.autocompletion

but ya even if it’s disabled by default and allow us to turn it on I’d appreciate that.

**Comment by nfm886** [comment]
> @nfm886 oh I see, I’ve used it in MacOS, windows, Nvidia shield and MiBox with no problems but I install this version of auto complete is where I’ve had the most success.
> 
> https://github.com/icpryde/plugin.program.autocompletion
> 
> but ya even if it’s disabled by default and allow us to turn it on I’d appreciate that.

OK. I can bring back this.
Maybe I should try to fix this add-on instead of removing this feature :P

**Comment by nfm886** [comment]
Just added this feature. Will be available with next update.
If something won't wrong, please open new issue.
