### ISSUE TITLE
[Feature Request] OSD Features

### ISSUE THREAD

**Issue by icpryde** [nfm886/skin.cosmic#11]
Hey so a few things seem to be missing with some OSD features from this skin:

Right now the OSD in cosmic is very bare bones and only showing the "simple" OSD as seen here.
 
![Screen Shot 2021-08-11 at 4 27 23 PM](https://user-images.githubusercontent.com/29389746/129102044-656612bd-0480-4dad-bf9c-5360d62287bd.png)

I would like to be able to see more options in the OSD to show the poster, movie title, movie summary and also the  codec information as well as seen here in resurrection:

![Screen Shot 2021-08-11 at 4 51 54 PM](https://user-images.githubusercontent.com/29389746/129102135-11b0115a-7a0a-4a5a-b46f-542251f945c8.png)

**Comment by icpryde** [comment]
Oh I did manage to find auto close OSD in settings it still seems very bare bones but that feature is there at least....the other things above still apply though ^

![Screen Shot 2021-08-11 at 5 05 10 PM](https://user-images.githubusercontent.com/29389746/129103273-e60ffdeb-e0c5-4f8f-baae-3abceea59147.png)

**Comment by icpryde** [comment]
Cleaned up the original post, hope that makes more sense now ^

**Comment by icpryde** [comment]
After further playing with the OSD I think it works just fine this isn’t necessary I’ll close this now

**Comment by nfm886** [comment]
Sorry, if I did not reply for this issue. Just think it's not necessary to see that all informations.
Basically when you watch a movie, you watch a movie not looking for informations about movie.
