### ISSUE TITLE
[Request] Focus onto a particular section on start up

### ISSUE THREAD

**Issue by rizreflects** [nfm886/skin.cosmic#14]
![IMG_20210813_211515.jpg](https://user-images.githubusercontent.com/76912707/129413979-a1e4ea57-dab0-4366-a95c-9c9bc84ab58b.jpg)

As you can see from the image, I have search on top of all the other sections. Due to this, the skin automatically shows the search section when my device starts up. If possible, could you add an option to let me pick the section to show on startup? For example, I'd like it to boot directly onto the movies section instead of the search section.

**Comment by nfm886** [comment]
I'm not sure if it's possible...
I will investigate it in free time.
