### ISSUE TITLE
[Bug] Genre, Studio info animation acting weird

### ISSUE THREAD

**Issue by icpryde** [nfm886/skin.cosmic#15]
Hey I'm not sure how to really describe it but the genre/studio info has a swipe up animation when it changes the information which flys over top the description text and so it looks a little wierd.

I think just a simple animation that switches from one to the other would be better or a quick fade but the swipe feels out of place here.

I made a video so you can see what i'm talking about.

![Screen Shot 2021-08-15 at 4 17 47 PM](https://user-images.githubusercontent.com/29389746/129491564-3576393e-60d3-4819-83b9-62bc8780ea59.png)

Link to video: https://streamable.com/g3q3ab

**Comment by nfm886** [comment]
Ok. I will try to improve it today :)

**Comment by nfm886** [comment]
I think we can close the issue. Animation has been changed :)
