### ISSUE TITLE
[BUG] Please make Kaito work with the Trailer Feature

### ISSUE THREAD

**Issue by icpryde** [nfm886/skin.cosmic#16]
I remember asking this from you on the resurrection skin and I'm again asking if this could be added to cosmic as well and have the trailer feature work with the Kaito add-on.

![Screen Shot 2021-08-16 at 5 58 10 PM](https://user-images.githubusercontent.com/29389746/129635843-6928fcae-b9f7-477b-9cc8-28ad371334f5.png)

As you can see right now i tried a bunch of trailers and none of them are working.

https://github.com/SwagOtaku/plugin.video.kaito

**Comment by nfm886** [comment]
Hey,
I think I fixed it in most of the cases...
Please download this zip file and do some tests: https://github.com/nfm886/skin.cosmic/archive/refs/heads/master.zip

**Comment by ViewAfterReview** [comment]
I tested this on TheOath and it always plays the trailer of the first item

**Comment by icpryde** [comment]
> Hey,
> I think I fixed it in most of the cases...
> Please download this zip file and do some tests: https://github.com/nfm886/skin.cosmic/archive/refs/heads/master.zip

@nfm886 just tested the trailer feature on kaito and its working, thank you!
