### ISSUE TITLE
[Feature Request] Different Viewtypes

### ISSUE THREAD

**Issue by icpryde** [nfm886/skin.cosmic#17]
I noticed right now we are limited to only 1 viewtype which is OK, but theirs several others that I like a lot more that I would really appreciate being added to the skin.

This is the current one:
![Screen Shot 2021-08-16 at 6 42 44 PM](https://user-images.githubusercontent.com/29389746/129638171-bf1285db-1de4-4042-9444-6868c4cbf665.png)

I would love some other options like the ones in Ressurection:

![Screen Shot 2021-08-16 at 6 44 50 PM](https://user-images.githubusercontent.com/29389746/129638285-97fb8ac4-8512-4c8c-99dc-efab36e817ec.png)

![Screen Shot 2021-08-16 at 6 44 59 PM](https://user-images.githubusercontent.com/29389746/129638298-d775eb2e-6c7c-4746-9544-f9e0c888fee7.png)

**Comment by nfm886** [comment]
I'm planning to add different view types.
First I want to sort out some other things.

**Comment by nfm886** [comment]
Closing for now. You will know when I add new view types.
