### ISSUE TITLE
[Feature Request] Checkmarks & Remaining episodes on posters 

### ISSUE THREAD

**Issue by icpryde** [nfm886/skin.cosmic#18]
I really like this feature when you get a green check mark knowing you finished a series or a remaining episode count on the top right corner as see here:

![Screen Shot 2021-08-16 at 6 44 36 PM](https://user-images.githubusercontent.com/29389746/129638466-fb0735c5-ae03-4964-ba82-12064b35400f.png)

Currently it looks like this and i don't see anything in the settings to turn it on?

![Screen Shot 2021-08-16 at 6 44 22 PM](https://user-images.githubusercontent.com/29389746/129638496-7a08eca5-02db-42ae-8336-17506b514af4.png)

**Comment by nfm886** [comment]
Yeah, this option is missing. I will add this soon :)

**Comment by nfm886** [comment]
Added those indicators lately. So I think we can close this ticket.
