### ISSUE TITLE
[BUG]No Multi Global Background 

### ISSUE THREAD

**Issue by AbdelkarimLamrini** [nfm886/skin.cosmic#19]
Can't seem to get the global background set up to cycle through images in a map.
The map is solely filled with images.
Each of these images works as a "Single" Global Background.

Thanks a lot for the amazing skin btw. Works really smoothly. ;)

**Comment by nfm886** [comment]
Sorry, I don't understand it well. What map do you mean?
I fixed multi images in global background yesterday.

**Comment by AbdelkarimLamrini** [comment]
Sorry if I wasn't clear, I meant a map in my download folder containing several wallpaper images. Maybe I have yet to update to the latest version.

Thank you for this reply.

Abdelkarim Lamrini
________________________________

**Comment by nfm886** [comment]
> Maybe I have yet to update to the latest version.

Yeah. Please check on the latest version. I believe it's fixed already.

**Comment by AbdelkarimLamrini** [comment]
Tyvm, the update fixed it, thanks for the quick replies.

**Comment by nfm886** [comment]
Awesome :)
