### ISSUE TITLE
[Bug] The Volume Slider looks like a mess. 

### ISSUE THREAD

**Issue by Goldenfreddy0703** [nfm886/skin.cosmic#20]
Hey so sorry for saying it looks like a mess, its not really a mess its just off and needs some fixing and a color change. 
![image](https://user-images.githubusercontent.com/62456796/129836725-5114c943-6b77-4338-8854-84636e004606.png)
If you can change the volume slider color from white to black to match its skin theme then that would be great. One last thing if you can is to move the volume symbol in the volume slider instead of hanging out of the right. Again thank you and hope your having a great day.

**Comment by nfm886** [comment]
What resolution you are using? 
It looks OK on my devices.

**Comment by Goldenfreddy0703** [comment]
1920 x 1080 sorry i was busy with coding stuff.

**Comment by Goldenfreddy0703** [comment]
oh....well im a dummy, turns out it was not on 1920 x 1080, that was myfault, sorry

Is there an option to change the volume slider from white to black?

**Comment by nfm886** [comment]
> Is there an option to change the volume slider from white to black?

I think, I can add this option.

**Comment by nfm886** [comment]
Ok. Added option to enable dark volume slider.
Will be available with today's update.

**Comment by Goldenfreddy0703** [comment]
Hey thank you so much and your the best. Best skin ever

**Comment by nfm886** [comment]
Thank you!
Have a nice day :)
