### ISSUE TITLE
[BUG] Subtitle offset does not follow custom colors

### ISSUE THREAD

**Issue by ViewAfterReview** [nfm886/skin.cosmic#21]
Skin Version: 1.0.19
Even though I change highlight and gradient color, the subtitle offset toggle stays at skin defaults colors.

![Untitled](https://user-images.githubusercontent.com/86300945/129861584-31083e29-86aa-4e5f-8ef6-207a0b76d110.png)

**Comment by nfm886** [comment]
Oh right. I know, there are some places where it does not follow selected colour.
I'm gonna to fill them one by one. Thanks for reporting it. I will fix it in a minute :) If you find other places where it's happens, please report me back :)

**Comment by nfm886** [comment]
Fixed highlight colour in most places: https://github.com/nfm886/skin.cosmic/commit/ee5b7d86014c03e727b3bc892db520a5d5ff0b94
There may be some text with default highlight colour instead of selected but I will fill those too :)
