### ISSUE TITLE
Adding Extra Icons for the Skin

### ISSUE THREAD

**Issue by icpryde** [nfm886/skin.cosmic#27]
Hey I made these icons that I throw into my skin but I was wondering if you wanted them to just add it officially to the list, this would also help me so i don't have to re-add them manually every update but also i'm sure other people would appreciate some extra icons too ^_^

Enjoy, and thank you for all the hard work!

Here they are in a zip file to save you some time but just in case I'll add them here individually as well:

[extraicons.zip](https://github.com/nfm886/skin.cosmic/files/7041653/extraicons.zip)

![AL](https://user-images.githubusercontent.com/29389746/130677717-af36ee73-d938-45b0-a648-2452ce9322ae.png)
![amazon](https://user-images.githubusercontent.com/29389746/130677718-0ecb9b79-5f44-4f94-8698-173f31cf9658.png)
![crunchyroll](https://user-images.githubusercontent.com/29389746/130677719-fea28bce-72c0-4c12-b525-d657f5bbb39e.png)
![dc](https://user-images.githubusercontent.com/29389746/130677723-447b94f8-7514-4dfe-8a31-537ba1f7fe09.png)
![disney](https://user-images.githubusercontent.com/29389746/130677725-d1e97d27-662c-4abb-b5c6-b67616156943.png)
![dragonball](https://user-images.githubusercontent.com/29389746/130677726-b463d3c4-ea6c-4c4a-aa6e-28a7b2afa85b.png)
![funimation](https://user-images.githubusercontent.com/29389746/130677728-c1174d16-3c85-48ca-96cc-513d135289ce.png)
![kitsu](https://user-images.githubusercontent.com/29389746/130677730-2d58f8aa-47ff-4962-b84a-3e4a54f80063.png)
![MAL](https://user-images.githubusercontent.com/29389746/130677731-ccc18d5e-b471-4f85-9908-0467a140bd00.png)
![marvel](https://user-images.githubusercontent.com/29389746/130677732-780270be-65f0-48d4-80a0-e799ebedc12c.png)
![naruto](https://user-images.githubusercontent.com/29389746/130677734-7c04125f-06cc-41c5-aac3-a342a5337ec0.png)
![onepiece](https://user-images.githubusercontent.com/29389746/130677736-b7027963-cb38-41eb-b5f8-42b33247e632.png)
![pokeball](https://user-images.githubusercontent.com/29389746/130677738-f7abc667-206e-4a53-b7b0-39d868af6355.png)
![prime](https://user-images.githubusercontent.com/29389746/130677739-2e52a129-0899-42ef-b4d7-030b5649bbb2.png)
![starwars](https://user-images.githubusercontent.com/29389746/130677740-432d816d-47ab-4eb5-84d8-b67a273e4f99.png)

**Comment by nfm886** [comment]
Sure, I will add them. Thanks!
