### ISSUE TITLE
[Feature Request] Can you add a Sqaure Widget Aspect in your skin?

### ISSUE THREAD

**Issue by Goldenfreddy0703** [nfm886/skin.cosmic#3]
Hey there, thank you so much for fixing the bugs in your skin. Your skin is really awesome and simple to use and lightweight and this could be the next skin for me in the future. One Feature Request that i would like you to add in the future is a Square Widgets Aspect for the menu so that i could use it for music or youtube channels or something. Again greatest skin ever and hope this request can be considered. 

![image](https://user-images.githubusercontent.com/62456796/128562070-3cf81024-38fe-4fad-808c-da03c0bf8d3c.png)

**Comment by nfm886** [comment]
Just added Square aspect ratio. I hope you meant this: https://imgur.com/Plfgh1V :)

**Comment by Goldenfreddy0703** [comment]
yes thank you very much
