### ISSUE TITLE
[Request] Netflix homescreen style as a selectable Media View type

### ISSUE THREAD

**Issue by Nuklear92** [nfm886/skin.cosmic#30]
As the title says, do you plan to eventually provide a Media View style that give us the same cool homescreen layout for shows, movies, episodes, etc. when navigating inside addons and not just for the Home Screen. Skins like, Titan Binge Mod, AuraMod, etc. gives you the option to have the same Netflix style as a selectable Media View which you can Lock and Unlock within add-ons different menus, lists. That way we can keep that Netflix vibe not just only when you have widgets in the homescreen.

**Comment by nfm886** [comment]
Yeah, I think it's a good idea. Will add it soon :)

**Comment by Nuklear92** [comment]
Thanks buddy, keep the good work! 😃👍

**Comment by nfm886** [comment]
Just added this view type. Please check for updates :)
Closing this ticket. If you find any bugs please open another one and report to me! Thanks :)

**Comment by Nuklear92** [comment]
Awesome! I'll let you know after I test. 🙂
