### ISSUE TITLE
[Bug] Next Up Thumbnail Info Dialog List

### ISSUE THREAD

**Issue by icpryde** [nfm886/skin.cosmic#34]
Alright just found another little bug, the screen was looking a little bare and Noticed the info Dialog wasn't showing up below the description as seen here:

![Screen Shot 2021-08-25 at 2 37 11 PM](https://user-images.githubusercontent.com/29389746/130849809-34d1b853-5269-462c-8a25-9bcb69b7f439.png)

Though if I wait about 5-10 seconds it will slowly fade in and finally show up as seen here:

![Screen Shot 2021-08-25 at 3 00 44 PM](https://user-images.githubusercontent.com/29389746/130849865-15ba4d5d-5e0c-4fc4-8aa2-e87af00a94b4.png)

Any other widget row the information shows up instantly so not sure for the reason of the delay specifically on this specific widget row which is using Next Up from Seren.

**Comment by nfm886** [comment]
After some thoughts. I think I won't touch it. It's not worth to play with it since it's displaying only in Vertical layout also it's part of it so... Let's leave it as it is. Closing for now.
