### ISSUE TITLE
[Bug] Pause and clear logo in OSD conflicting 

### ISSUE THREAD

**Issue by icpryde** [nfm886/skin.cosmic#39]
I like the changes you made to the OSD but noticed a few little things that might need a tiny bit of tweaking.

When you Pause you can see it has giant word PAUSED in the center of the screen which was fine but now that the clear logo is showing up its overlapping itself ontop of the paused word which looks messy.

Not sure if maybe its best to move the paused word to the top of the screen maybe? or somewhere else just so nothing overlaps.

I also noticed a tiny white dot bottom left corner, no idea what that is its so minor but just bringing it to your attention too.

![Screen Shot 2021-08-27 at 4 10 52 PM](https://user-images.githubusercontent.com/29389746/131183477-674e32bb-a1ee-4680-9f5b-13a4497cda87.png)

**Comment by nfm886** [comment]
Moved seeklabel a little bit higher. This should do the job just fine.
About this dot I'm not sure what is it. I will look into it. Does it happen on every movies/tv show?

**Comment by icpryde** [comment]
the paused being moved up looks good and the white dot seems to be gone with the newer update....it was showing up for different shows but now its not showing up at all... soo whatever it was its gone now lol

**Comment by nfm886** [comment]
> the paused being moved up looks good and the white dot seems to be gone with the newer update....it was showing up for different shows but now its not showing up at all... soo whatever it was its gone now lol

Ok. So we can close. Thanks :)
