### ISSUE TITLE
[BUG] Showing Information after search

### ISSUE THREAD

**Issue by ViewAfterReview** [nfm886/skin.cosmic#40]
Showing information in an item that you search overlaps with the search making it impossible to read

![Untitled](https://user-images.githubusercontent.com/86300945/131227737-6ee6ba43-7b1c-4297-944a-61e57ed08b24.jpg)

**Comment by nfm886** [comment]
Oh damn. This is one big mess :P
What version of skin you are using?

**Comment by ViewAfterReview** [comment]
v1.0.34 but I test it again at v.1.0.35 same result

**Comment by nfm886** [comment]
> v1.0.34 but I test it again at v.1.0.35 same result

Fixed in 1.0.36. Please check for updates. Thanks for your report! :)
