### ISSUE TITLE
[Request] Flixview trailer feature

### ISSUE THREAD

**Issue by icpryde** [nfm886/skin.cosmic#41]
I was just testing out the new flixview viewtype you set up but i was just thinking in this viewtype it would be really cool if the trailer feature worked here too since it seems douable and would fit the netflix style i think?

just a suggestion.

![Screen Shot 2021-08-28 at 3 30 18 PM](https://user-images.githubusercontent.com/29389746/131228847-273d2724-17c9-4c5c-8582-59d7c6c13f1d.png)

**Comment by nfm886** [comment]
For now I'm not planning to do this. Trailers are still experimental feature.
