### ISSUE TITLE
[Bug] Longer Titles on Menu get Truncated when Highlighted

### ISSUE THREAD

**Issue by prazsky** [nfm886/skin.cosmic#45]
When a longish title is added (e.g. "Trending Movies") it displays fine when not highlighted, but when highlighted, it gets truncated as the behavior for highlighting is to bolden and make the text bigger. I feel allowing overflow to the right would be the better default as truncating looks very bad

**Comment by nfm886** [comment]
I think it's fixed now since I changed fonts a little bit. Now the text is not that bold, so should not be truncated. Of course there is a limit for displaying text.
