### ISSUE TITLE
[Bug] Widget 14 rows max

### ISSUE THREAD

**Issue by rijsab** [nfm886/skin.cosmic#48]
Hi,

After the 14th widget Row the rows are behaving very strange and are cutting off the posters. Is it possible to increase the widget rows please. 

Thanks.

**Comment by nfm886** [comment]
Just tested this on my setup with 17 rows, everything seems to be OK.
Are you using different aspect ratios? Some more info or screen recording would be appreciated :)

**Comment by rijsab** [comment]
Hi, I use only the first row as landscape, the other rows are just posters. Once at the last widget row they will behave strange and showing only half of the posters. Will try to get you a video.

**Comment by nfm886** [comment]
Unfortunately can't reproduce it: https://streamable.com/q2wgz5 :/

**Comment by rijsab** [comment]
Me neither anymore, seems to work back now. I think it had to do with Autowidget as I am not using this addon any more. 

Sorry for bothering you.

**Comment by nfm886** [comment]
Glad it's working :)
