### ISSUE TITLE
[Request] Add ratings and fixed widget scrolling to flixview

### ISSUE THREAD

**Issue by rizreflects** [nfm886/skin.cosmic#49]
As the title states, could you please add these 2 things to the flix view so it's more similar to the homescreen? 

Thanks for all your work.

**Comment by nfm886** [comment]
I will add this. Hope it will be available with today's update in the evening :)

**Comment by nfm886** [comment]
Just added in last update :)

**Comment by rizreflects** [comment]
![IMG_20210902_193329.jpg](https://user-images.githubusercontent.com/76912707/131898104-1ea2a85e-e8c3-43e2-8fa6-40df2ba84553.jpg)

Minor bug since the update (watched indicator should be in front)

Also, the scrolling animation seems a lot slower compared to the one on the homepage.

**Comment by nfm886** [comment]
> Minor bug since the update (watched indicator should be in front)

Damn, I did not notice it before an update. However it's fixed already :)

> Also, the scrolling animation seems a lot slower compared to the one on the homepage.

I know. I wanted to experiment a little bit and mimic "Netflix" vibe^^ Probably I will try to implement this scrolling to home screen.

**Comment by rizreflects** [comment]
![Uploading a8{30a451d} (2699c436-9615-4db3-8db1-183ab1164a22 id=0x7f0a037b) …]()

If I click the next page item (as shown above) it loads like this now 

![IMG_20210902_193913.jpg](https://user-images.githubusercontent.com/76912707/131899163-9fece29c-bb01-4123-a1f3-ad01e807b160.jpg)

Example from another list: 

![IMG_20210902_193939.jpg](https://user-images.githubusercontent.com/76912707/131899194-bd9e311b-db80-46ac-90a0-bd001a60e963.jpg)

Looks a bit strange.. just thought I'd point it out.

**Comment by nfm886** [comment]
> ![IMG_20210902_194106.jpg](https://user-images.githubusercontent.com/76912707/131899478-1f1cc91d-02a3-47a2-a095-ab35a88978a9.jpg)
> 
> If I click the next page item (as shown above) it loads like this now
> 
> ![IMG_20210902_193913.jpg](https://user-images.githubusercontent.com/76912707/131899163-9fece29c-bb01-4123-a1f3-ad01e807b160.jpg)
> 
> Example from another list:
> 
> ![IMG_20210902_193939.jpg](https://user-images.githubusercontent.com/76912707/131899194-bd9e311b-db80-46ac-90a0-bd001a60e963.jpg)
> 
> Looks a bit strange.. just thought I'd point it out.

Thanks for pointing this out. Reopened issue since it should be improved for sure.

**Comment by nfm886** [comment]
Are you using AutoWidget to achieve this button to load next page?

**Comment by rizreflects** [comment]
Yes I am.. but the same thing will happen when using seren directly.

**Comment by nfm886** [comment]
I just tested it on my setup. Everything works as expected: https://streamable.com/539cz2 
I assume something is broken with yours.

**Comment by rizreflects** [comment]
Even in your video the problem was there.. the only difference is it loaded faster. Look at the first time you pressed next on tmdbhelper.. you can see the info button and also the white outline that goes around posters. Try loading a list that takes longer.. it seems the one you loaded was already cached? It loaded very fast.

**Comment by rizreflects** [comment]
![Screenshot_20210905_133645_com.vivaldi.browser.jpg](https://user-images.githubusercontent.com/76912707/132127020-6f52c93d-3a8b-4be4-89f0-d3fa2a2a4a04.jpg)

See here? In this case it never showed the fanart which happens sometimes.

**Comment by nfm886** [comment]
> it seems the one you loaded was already cached? It loaded very fast.

It was not cached. I did restart Kodi before testing.

>  Even in your video the problem was there.. the only difference is it loaded faster. Look at the first time you pressed next on tmdbhelper.. you can see the info button and also the white outline that goes around posters. Try loading a list that takes longer..

Wait, so your problem is with this info tag and poster highlight? I'm confused now -.-
If so, I will correct it soon. I know it sometimes happen.

If your problem is related to not loaded content after pressing next page. I don't know, as you saw, everything was working on my setup so would be nice if you can do test on fresh install or with add-ons enabled one by one to see what causing the issue.

If I can't reproduce it, I can't do anything with it... Sorry

**Comment by rizreflects** [comment]
I think you might be confusing my issue with another one.. the next button has always functioned for me.. it loads fine. The only problem was how it looked while it loading. If you're looking into that then that's fine :) 

One more question though, how does Kodi run so fast for you? Are you running it on windows? If not please tell me which device you're using as I'll need to purchase one myself.

**Comment by nfm886** [comment]
> The only problem was how it looked while it loading. If you're looking into that then that's fine :)

Oh my friend. Sorry for misunderstood :) I will fix it soon, I know about it and it's annoy me too :P 


> One more question though, how does Kodi run so fast for you? Are you running it on windows? If not please tell me which device you're using as I'll need to purchase one myself.

It's my dev laptop with R5 4600H, GTX 1650 (which is not in use^^), 16GB RAM in DualChannel 3200MHz.
My OS is Linux but I think on Windows it should works fine too.
It's not a most powerful device, I would say it's mid range but I can do my job on it so it's perfect :)

**Comment by nfm886** [comment]
> I think you might be confusing my issue with another one.. the next button has always functioned for me.. it loads fine. The only problem was how it looked while it loading. If you're looking into that then that's fine :)

I think it's sorted out. Would you like to test it?
Please download this zip file: https://github.com/nfm886/skin.cosmic/archive/refs/heads/master.zip

**Comment by rizreflects** [comment]
Just tested on windows and it looks like it's working fine now. Thanks a lot.

**Comment by nfm886** [comment]
> Just tested on windows and it looks like it's working fine now. Thanks a lot.

Thank you.
