### ISSUE TITLE
[Bug] Widgets like Weather or Settings Widgets are not displayed

### ISSUE THREAD

**Issue by Goldenfreddy0703** [nfm886/skin.cosmic#5]
I would not consider this as a bug but when using Widgets on your menu like Weather or Settings, they don't display. They just keep loading and nothing happens. 
![image](https://user-images.githubusercontent.com/62456796/128566631-cb064d65-9d20-458b-9e57-2773d9a2e0a2.png)
![image](https://user-images.githubusercontent.com/62456796/128566697-6b543ae8-3a0f-4894-bdf7-931c09eff493.png)
![image](https://user-images.githubusercontent.com/62456796/128566818-1a05c250-d048-4ade-8271-6350f80b294a.png)

You may want to look into that or if you have not implanted these then you may want to do this in the future when its needed. 
Again, thank you for looking through this.

**Comment by nfm886** [comment]
They are not implemented yet :D

**Comment by Goldenfreddy0703** [comment]
oh ok thank you for telling me.

**Comment by nfm886** [comment]
Just added Settings and Weather widgets. They are ready in v1.0.5

**Comment by Goldenfreddy0703** [comment]
Hey sorry it took me a long time to respond but everything seems to be working but the only thing that's not working is switching between locations for the weather and that's about it.
![location](https://user-images.githubusercontent.com/62456796/128896513-26e1949c-73ea-4137-bdce-dd95c3e8d36d.PNG)
I really like the weather widget its different from other skins i have seen and it gives you weather maps and i thought that was cool. 

Again, Thank you very much.

**Comment by nfm886** [comment]
Do you mean that button where it shows "Press OK to switch between locations"?
I will look into it.

**Comment by Goldenfreddy0703** [comment]
Yes I do mean that button you mentioned. Thank you

**Comment by nfm886** [comment]
> Yes I do mean that button you mentioned. Thank you

Ok, it's fixed now.

**Comment by nfm886** [comment]
Just pushed an update. Changes are ready in v1.0.6

**Comment by Goldenfreddy0703** [comment]
Nice Thank you very much
