### ISSUE TITLE
[Request] 2 things from titan bingie

### ISSUE THREAD

**Issue by rizreflects** [nfm886/skin.cosmic#50]
I know you don't like copying from other skins and much prefer to come up with your own ideas.. I totally respect that.. So if you deny these 2 requests no hard feelings. That being said there were 2 features that really kept taking me back to titan bingie over the years. Then again, its not really a titan bingie feature, but more of a netflix feature. 

The first one is a spotlight widget as shown below:

![bingiespotlight](https://user-images.githubusercontent.com/76912707/131905733-cf0f9972-bba6-4f8b-a9d0-c88babbc9c4c.jpg)

As you can see it looks pretty good. It sits just on top of the other widgets but uses the full screen. Even though it only shows one movie, its actually functional. For example, I can create a list like one I made here  https://trakt.tv/users/rizreflects/lists/spotlight-f75b93d1-9e5e-4bab-933d-73e69f057867?sort=random,asc and set it at random through trakt. I can also filter the ratings to only include well-rated movies. This is a great way to find movies you would have otherwise never found.

My second request is purely asthetic.. but I'm sure someone like you (a person who has an eye for design) could appreciate this:

![toponimdb](https://user-images.githubusercontent.com/76912707/131906457-da866f12-e922-4dcd-8ada-83a22e91d46b.jpg)

I'm referring to how it says 'no 165 on IMDB today'.  Its aesthetically pleasing and makes it seem like the skin is integrated with IMDB. Its a small touch that goes a long way. Of course currently on cosmic there is a small badge which indicates the IMDB top 250.. But imo it just doesn't look as good as this.

To be honest, these are the only 2 things I really miss about using titan bingie so I thought I'd bring it to your attention and maybe you could do something similar in the future. Feel free to disregard these requests if it doesn't fit your vision though.. No worries at all. Thanks for all your work as usual.

**Comment by nfm886** [comment]
Thanks for your ideas. I will look into it in the future. Now there is some other things to improve.

**Comment by nfm886** [comment]
Currently implemented something similar: https://streamable.com/3doe3h
It will be available with today's update. We can close this ticket. Thanks

**Comment by rizreflects** [comment]
I really like the flix spotlight. But could you make it appear by pressing 'select' instead of 'back'? I tend to use the back button to access hubs (like movies / TV shows)

**Comment by nfm886** [comment]
> I really like the flix spotlight. But could you make it appear by pressing 'select' instead of 'back'? I tend to use the back button to access hubs (like movies / TV shows)

Yes. I'm planning to improve this a little bit. There will be an option to choose between back button and select :)

**Comment by rizreflects** [comment]
Quick question- when clicking on 'search cast' it takes about 15-20 seconds to load on my shield.. is it supposed to take this long or are you still working on that?

**Comment by nfm886** [comment]
> Quick question- when clicking on 'search cast' it takes about 15-20 seconds to load on my shield.. is it supposed to take this long or are you still working on that?

Basically this whole feature is WIP and early stage. I will improve this stuff for sure.
Probably I even know why it's that slow, but I will fix it tomorrow.
Just wanted to push an update to test it on my devices :D
