### ISSUE TITLE
[Bug] Do Not Hide Showcase removing clear logo

### ISSUE THREAD

**Issue by icpryde** [nfm886/skin.cosmic#54]
I noticed when the trailer starts it hides the clear logo and not sure why it does that, i know you can turn on or off "do no hide show case" but if you have it on it removes the clear logo when the trailer starts. 

I think it should leave the clear logo and description when the trailer starts when you have "do not hide showcase" set to on.

When you have it set to off than it should remove clear logo and description to only display the trailer.

![Screen Shot 2021-09-04 at 3 47 29 PM](https://user-images.githubusercontent.com/29389746/132106393-d438d527-2d67-42a3-8b3c-45f396fa82ce.png)

**Comment by icpryde** [comment]
So after a little more testing if I turn on "animate clearlogo" the clear logo stays while the trailer plays but this seems incorrect because the clear logo doesn't animate.

![Screen Shot 2021-09-04 at 3 52 31 PM](https://user-images.githubusercontent.com/29389746/132106454-8fa582e6-8d30-4745-85d8-f2f349d50b05.png)

So when i have the above settings set i'm getting the desired effect which is the trailer playing but also leaving the description and clear logo in view.

**Comment by nfm886** [comment]
The behavior of this option should be now corrected.
I was kind of tired while implementing this so it's hard to understand why it worked like before :P
You can test it: https://github.com/nfm886/skin.cosmic/archive/refs/heads/master.zip and give me feedback please if it works as it should now.
