### ISSUE TITLE
Add option open extendedinfo

### ISSUE THREAD

**Issue by trkselim** [nfm886/skin.cosmic#55]
Hi
Can you add option force open extendedinfo (diamondinfo) as default info for movies an tv shows the there’s developer  make it work with kodi 19
Here’s the dev github link 
[Extendedinfo ](https://github.com/henryjfry/repository.thenewdiamond) 
It’s really fast with kodi 19

I hope you can  try it 
Have a nice day

**Comment by rijsab** [comment]
Yes indeed fast but I dont get it to work? I tried embycon and plexkodiconnect and giving error to play? Both players as addon are working so no issue with connectivity.

**Comment by nfm886** [comment]
I'm not planning to add this.

**Comment by rijsab** [comment]
I agree, force diamondinfo to open is not really necessary and do not see the benefits of it.. just open it from context menu if required but all information is available if you open information screen as well..

**Comment by nfm886** [comment]
Yeah but it require some dependencies. We have TMDbH and Embuary for that. It's not needed to add more. Sorry
