### ISSUE TITLE
[BUG] Colour issue in Classic Vertical Layout

### ISSUE THREAD

**Issue by luckylukz02** [nfm886/skin.cosmic#56]
I enjoy using Classic Vertical Layout

I have an issue with colour in this view.  

When I first launch Kodi. There's alot of white on the left with the names barely visible.

![Screenshot_20210907-215735_WhatsApp](https://user-images.githubusercontent.com/80491975/132410354-4dbb1228-8f86-4180-a876-508c9fd1c571.jpg)

After I navigate the main menu it turns to a strange shade of brown.

![Screenshot_20210907-215739_WhatsApp](https://user-images.githubusercontent.com/80491975/132410491-87885e4c-d0a6-4f53-bf13-540bf227b7fb.jpg)

This issue is shared by a friend who says it was previously transparent. 

v1.0.46

**Comment by rijsab** [comment]
Did you turn off match poster colour in settings? If not, did you play around with colour %?

**Comment by luckylukz02** [comment]
Match poster colour is enabled.
(Assuming this is Match overlay colour from image)

Overlay playground set as:
Alpha : 40% Luminance: 25% Saturation: 35%

**Comment by rijsab** [comment]
Not sure and perhaps Heppen can support in this. I matched my settings with yours and no issue on my device.

**Comment by luckylukz02** [comment]
After toggling Match overlay colour from image it seems like the brown does go away after focusing on different posters. The brown is actually from my current first poster when Kodi loads.

However when I start Kodi it is still defaulting to what is actually on screen a light grey.

![Screenshot_20210907-215735_WhatsApp](https://user-images.githubusercontent.com/80491975/132415798-34ab917b-0ec5-4d7c-a746-0833482c28cc.jpg)

My device is on PC running Libreelec. Friends device is PC running Windows.

**Comment by nfm886** [comment]
> However when I start Kodi it is still defaulting to what is actually on screen a light grey.

I should set a fallback colour based on Highlight colour which I did not. I will fix it today.

**Comment by nfm886** [comment]
It should be fixed now. I will push an update later.
Thanks for your report :)
