### ISSUE TITLE
Limit on widget rows

### ISSUE THREAD

**Issue by rijsab** [nfm886/skin.cosmic#57]
Hi, after 21 widget rows the 22nd row is acting very strange by showing the posters in half. Is this a bug or just me? I am using AutoWidget for most of my widgets. 

Thanks.

**Comment by nfm886** [comment]
It's a bug. Basically I made a limit to 20 rows and though it's enough ^^
I will change it later. Sorry.

**Comment by rijsab** [comment]
No problem. It is just me liking widgets and with your skin things are fast enough to have more widgets :D

**Comment by nfm886** [comment]
Just increased widget rows limit to 40. It should be enough until I found a way to make it dynamic and "unlimited": https://github.com/nfm886/skin.cosmic/commit/142bc0fc0b1c80f79c2d8c18afe324b0796a4d50 Please try it and give me feedback if it works.

**Comment by rijsab** [comment]
Thanks mate. I have tested and still same behaviour with 23 widgets..

**Comment by nfm886** [comment]
> Thanks mate. I have tested and still same behaviour with 23 widgets..

Ahh yeah. You just reached max height of the widget rows :roll_eyes: haha :)

Please test this one: https://github.com/nfm886/skin.cosmic/commit/e4cc3494b36b7f47289853144df3dd4127b54ce6

**Comment by rijsab** [comment]
This worked for me. Thanks!

**Comment by nfm886** [comment]
Glad to hear :)
