### ISSUE TITLE
[Request] Transparent sidebar

### ISSUE THREAD

**Issue by luckylukz02** [nfm886/skin.cosmic#58]
Is it possible to have an option for the sidebar on vertical classic layout to be transparent.

![20210909_202930](https://user-images.githubusercontent.com/80491975/132750748-f108e73e-e11e-43bd-b4c0-7b6d47282d6f.jpg)

I have tried this by changing the gradient and highlight colour to #0000ffff. However this has other implications throughout the skin.

I think it looks better than this:

![20210909_202118](https://user-images.githubusercontent.com/80491975/132750304-e9ded89f-9d70-4bc3-8733-b1cd212a1f58.jpg)

**Comment by nfm886** [comment]
Yes.
As I said before, Classic layout require some attention and improvements. Probably I will add this option.

**Comment by luckylukz02** [comment]
Perfect, look forward to it.

**Comment by nfm886** [comment]
It's transparent after last commits. I will improve it soon :eyes:
