### ISSUE TITLE
[Bug] Veiw Types wont let you change veiws in update skin 1.0.1

### ISSUE THREAD

**Issue by Goldenfreddy0703** [nfm886/skin.cosmic#6]
![image](https://user-images.githubusercontent.com/62456796/128568631-8adda056-2b3c-47da-b1b0-5fd016050f32.png)
Sorry for sending too many issues but i encountered another bug with your View Types, I believe on 1.0.1, you were allowed to change the View Types but on this version you can't for some odd reason. You may want to look into that and see if this is a bug or not cause im not too sure on this but i've noticed it happening today. 

Btw, Veiwtypes that are on list Veiw may not give you the option to change the Veiwtype.

**Comment by nfm886** [comment]
I did not touch it since last update. I believe there is no other view types for YouTube.
If you can see in another location, movies for example, there are several view types to choose from.
In the future I will fill those "lacks" with some view types.

**Comment by Goldenfreddy0703** [comment]
Ok thank you, it happened to seren, themoviedb helper, and soundcloud

**Comment by nfm886** [comment]
Hey, I see the issue there. 
Do you know if it worked before?

**Comment by Goldenfreddy0703** [comment]
I believe it was working on update 1.0.0 cause when i was first messing with the skin and getting the feel of it, i stumbled upon view typed and tried them out.

**Comment by nfm886** [comment]
Ok, thanks. I will look into it. Meanwhile, I think I found a fix for submenu bug.

**Comment by Goldenfreddy0703** [comment]
I noticed and tried it and it is amazing, one thing about the submenu fix i notices is that the icons are not displayed in the submenu but still good.

**Comment by nfm886** [comment]
Ok. Just investigated the issue. There is no view types for that view in Estuary also. 
They will appear when I will add them.
For now, we can close the issue.
