### ISSUE TITLE
Default font

### ISSUE THREAD

**Issue by papadcha** [nfm886/skin.cosmic#60]
Must use a Unicode font as default or leave older default font as an option. Arial isn’t nice as a display font.

**Comment by rijsab** [comment]
A question mark would increase your chanses ;)

**Comment by nfm886** [comment]
There is no "must", there is only "can".
Previous font was not fully compatible with Kodi 20 Nexus so I decided to change it.
This font should work with most languages and if not, there is Arial.
2 fonts are enough. I won't include more. I don't want additional work to do to support more fonts.
