### ISSUE TITLE
[Bug] Youtube Widget

### ISSUE THREAD

**Issue by luckylukz02** [nfm886/skin.cosmic#62]
I am using the YouTube widget however on selection to play on any widget results in flix spotlight exiting.

![20210912_233420](https://user-images.githubusercontent.com/80491975/133299384-3f78a842-1754-44ca-9f57-5a3103c73c12.jpg)

![20210912_234211](https://user-images.githubusercontent.com/80491975/133005077-e668d701-e268-463f-a8cb-103feedcd709.jpg)

I feel as if this wasn't a problem before the introduction of flix spotlight.

Also the 0% match wouldn't be required here.

v1.0.50

**Comment by luckylukz02** [comment]
Same issue exists for music addon I'm using:

https://github.com/spacys/mediathek

![20210915_002246](https://user-images.githubusercontent.com/80491975/133346651-a981ab6f-c6a4-4d29-93fc-e2afe43d8677.jpg)

![20210915_002237](https://user-images.githubusercontent.com/80491975/133346662-294eb656-7789-42e6-bba3-5ad2a91be853.jpg)

**Comment by nfm886** [comment]
Hi,
Thanks for your report.
I made small change. Would be nice if you can test it: https://github.com/nfm886/skin.cosmic/archive/refs/heads/master.zip and give me a feedback.

**Comment by luckylukz02** [comment]
I can confirm this has resolved the issue for YouTube widgets.

However it has caused a different behaviour for music. Widgets to my music addon work fine now like the YouTube addon.

However when I select a track from a widget I get taken to a page like this:

![20210915_103140](https://user-images.githubusercontent.com/80491975/133409586-f325e61a-f1b8-4a01-9c7e-6571650b839a.jpg)
(Notice it says Video)

**Comment by nfm886** [comment]
Ok. So music widget require different action to be performed after pressing play button.
I will add some music to my local library to see how it works and will back with fix I hope :)

**Comment by nfm886** [comment]
Hi @luckylukz02,
Just tested this on my machine with music widgets. Seems that works fine. The only issue I see is, it stopping music from playing in background after going back. So this is something what needs improvement for sure.
Please take a look: https://streamable.com/s5kn8r
