### ISSUE TITLE
[Question] I feel really dumb but how do you access the submenu on the menu

### ISSUE THREAD

**Issue by Goldenfreddy0703** [nfm886/skin.cosmic#7]
Hey so feel really dumb but im on the vertical menu and idk how to access the submenu items i made. 
![image](https://user-images.githubusercontent.com/62456796/128611873-0f4608f2-1413-4bd3-ace2-c1e41a31077b.png)
Could you please show me how to access my submenu items on the home menu? I feel dumb or i maybe not doing something right. 

On auramod Its easy to access submenu item but on this skin, i cannot find them. 
![image](https://user-images.githubusercontent.com/62456796/128611919-c4fc9529-2caa-41a2-91e4-c409f68a9f7e.png)

**Comment by nfm886** [comment]
I just broke it. In vertical layout submenu does not works :< Only in horizontal layout. I'm working on fixing it.

**Comment by Goldenfreddy0703** [comment]
Oh ok thank you, I felt really dumb and I could not find it anywhere.
