### ISSUE TITLE
After update to 1.0.55 can't launch any widget item with spotlight disabled

### ISSUE THREAD

**Issue by meesterexx** [nfm886/skin.cosmic#73]
As title, with spotlight disabled or trigger spotlight on select disabled, no widget item (favorites or not favorites) will launch. Must enable spotlight and use play button or long press > information > open to launch.

**Comment by nfm886** [comment]
Thanks! It should be fixed now. Please download this zip file and do some tests: https://github.com/nfm886/skin.cosmic/archive/refs/heads/master.zip :)

**Comment by ViewAfterReview** [comment]
> Thanks! It should be fixed now. Please download this zip file and do some tests: https://github.com/nfm886/skin.cosmic/archive/refs/heads/master.zip :)

Hey it works for me, It would be awesome if you could push it!

**Comment by nfm886** [comment]
> > Thanks! It should be fixed now. Please download this zip file and do some tests: https://github.com/nfm886/skin.cosmic/archive/refs/heads/master.zip :)
> 
> Hey it works for me, It would be awesome if you could push it!

Sure, I will push it asap since it's critical bug. However I want to finish just one thing before ;)

**Comment by nfm886** [comment]
Update is pushed already. So we can close the issue :)
