### ISSUE TITLE
Spotlight seems to be broken

### ISSUE THREAD

**Issue by icpryde** [nfm886/skin.cosmic#75]
I noticed with the latest update the spotlight feature seems to be broken, when I activate it this is all I see now, everything just goes black. 

![Screen Shot 2021-10-03 at 2 51 37 PM](https://user-images.githubusercontent.com/29389746/135767506-a8d80a7d-4272-4b02-a269-68469a7dfd68.png)

**Comment by nfm886** [comment]
Are you on latest skin version?

**Comment by icpryde** [comment]
ya i'm on 1.0.57

![Screen Shot 2021-10-03 at 2 56 38 PM](https://user-images.githubusercontent.com/29389746/135767599-8eda38ef-a59b-4e25-8583-78da1915869c.png)

**Comment by angelitto2005** [comment]
Yep, its broken for me too, on OSMC. I saw it last night. I will wait for an update.

**Comment by nfm886** [comment]
Thanks for your reports!
It should be fixed now :) I will push an update soon.
