### ISSUE TITLE
Trailer behaviour is different now?

### ISSUE THREAD

**Issue by icpryde** [nfm886/skin.cosmic#78]
I noticed the trailer behaviour changed and wasn’t sure if this was intentional or not? Now when the trailer starts I can keep scrolling while it plays the trailer in the window. 

The old behaviour was the moment I hovered over another item it stopped the trailer then started the 15 second timer and than started that trailer if I remained hovered on the poster.

if this new behaviour is intended how do I start a new trailer when one is currently playing?

here’s a video showing what I mean:

https://streamable.com/wsvjpu

**Comment by nfm886** [comment]
It should be fixed with this commit: https://github.com/nfm886/skin.cosmic/commit/04b1080d63c6b89dc7044f675939c86c513417d2
