### ISSUE TITLE
Spotlight goes black 

### ISSUE THREAD

**Issue by icpryde** [nfm886/skin.cosmic#79]
I noticed some weird behaviour again from spotlight, when activated the poster from the right side disappears and just shows black now?

here’s a video:
https://streamable.com/szxmu8

**Comment by nfm886** [comment]
Are you using latest 1.0.59 version? How you trigger Flix spotlight? By pressing Back or OK button?

**Comment by icpryde** [comment]
@nfm886 ya I’m on 1.0.59 it had the same problem on 1.0.58 as well.

I press the back button to trigger spotlight

**Comment by nfm886** [comment]
Hey,
Is the issue still there?
Sorry, I had a little rest. From what I have tested just now, it seems it works and I don't remember if I did something to it hehe :D
