### ISSUE TITLE
Zmiana koloru...

### ISSUE THREAD

**Issue by Katapulta** [nfm886/skin.cosmic#80]
Genialny skin. TO na dzień dobry.  Natomiast muszę zapytać o jedno - może ja nie umiem znaleźć, ale po aktializacjo do najnowszej wersji... przy zmianie kolorów - podświetlania , gradientu... zmienia się kolor całego skina. Wczesniej "belki" menu były chyba przezroczyste - albo można było je tak ustawić... a teraz... są takiego koloru jakie ustawię sobie podświetlenia... prawdę mówiąc... wcześniej było lepiej... :P No i tapety teraz tak dziwnie "obcięte" się wydają.. 
![kodi_RYTCjGpT9J](https://user-images.githubusercontent.com/26973858/136832146-77966b7e-303f-4299-9dae-2a4911604beb.png)

**Comment by nfm886** [comment]
Dzisiaj wieczorem wypuszczę aktualizację, która wprowadzi opcję do wyłączenia tych nakładek.
