### ISSUE TITLE
[Feature Request] Screensaver

### ISSUE THREAD

**Issue by starmanrf** [nfm886/skin.cosmic#83]
Hi,

Thanks for your hard work on this skin. Minimalistic, fast and looks great.

Hoping it's okay for a request... Wonder if it would be possible to incorporate the Arctic Horizon's skin screensaver xml code (allowing your skin to work with drinfernos Arctic mirage screen saver).

Think I read you're on a break from cosmic for a little while , so I hope you enjoy the festive season  👍

**Comment by nfm886** [comment]
Hey, thanks for your request :)
I'm not planning to do this. Kodi has it's own screensaver and I was using it. Never needed anything "third-party".

> Think I read you're on a break from cosmic for a little while , so I hope you enjoy the festive season +1

I'm fine :) It's not necessary true. I was working on new skin based on Cosmic, called Primus. I was planning to release it near the xmas but I did not think I won't have that many time to finish it in time, so it will happen a little bit later.

**Comment by starmanrf** [comment]
Aye that's a fair point... Now I think about it I think I'll ask Drinferno if he could make it a standard kodi screen saver rather than skin dependent.

Sounds like your keeping busy, I look forward to any skin you work on, I'll look forward to testing primus when it comes around👍 all the best.

**Comment by nfm886** [comment]
> Aye that's a fair point... Now I think about it I think I'll ask Drinferno if he could make it a standard kodi screen saver rather than skin dependent.
> 
> Sounds like your keeping busy, I look forward to any skin you work on, I'll look forward to testing primus when it comes around+1 all the best.

If I can recommend something, I would go with Aerial. Pretty nice screensaver :)

**Comment by starmanrf** [comment]
Thanks... Yeah I have it installed.. Some top quality images. 

I Really like Arctic mirage as it allowed for custom paths from any video add on and would display fullscreen fanart, clearlogo, ratings and plot (although I edited the xml so it only showed the fanart and clearlogo if available). I'm surprised nobody has created a similar kodi screensaver as its a great concept.

Think I'll make it my new years resolution to learn more about coding and give it a go myself 🤔😀👌
