### ISSUE TITLE
[Bug] Spotlight background goes black

### ISSUE THREAD

**Issue by icpryde** [nfm886/skin.cosmic#84]
When enabling spotlight the background image goes black as seen here.

![Screen Shot 2022-01-03 at 3 40 04 PM](https://user-images.githubusercontent.com/29389746/147978909-9d76fe18-5ce5-4c18-930f-365cd65284ab.png)

![Screen Shot 2022-01-03 at 3 40 10 PM](https://user-images.githubusercontent.com/29389746/147978925-cc1100e3-bc5a-465b-826d-a35d70aa8fab.png)

**Comment by nfm886** [comment]
Yeah, I'm working on it right now. Unfortunately I can't reproduce the issue: https://streamable.com/hou4mv :(
Any tips how to make it black? :D Also I see on the screenshot something weird with buttons which is not noticeable on my video.
