### ISSUE TITLE
[Bug] Trailer continuously plays despite hovering over another widget

### ISSUE THREAD

**Issue by icpryde** [nfm886/skin.cosmic#85]
The trailer once it starts playing it will keep playing that same trailer despite me hovering over another poster within my widgets and won't ever change to another trailer until i open the trailer to full screen to hit the stop button.

here's a video:

https://streamable.com/4w14yk

**Comment by nfm886** [comment]
Hey,
It is fixed in latest master brach: https://github.com/nfm886/skin.cosmic/archive/refs/heads/master.zip
I just did not push an update yet.
