### ISSUE TITLE
[Feature Request] Full Screen Spotlight View

### ISSUE THREAD

**Issue by icpryde** [nfm886/skin.cosmic#9]
So in Arctic Horizon they have this full screen spotlight feature which I really like and you can do a lot of different things with it but its nice for example to have this spotlight feature show up in sections you don't have widgets like "search" or "exit" because otherwise its just a black background.

Heres an example:

![126048063-09febb39-8673-4c5b-9260-eefb64e66ff5](https://user-images.githubusercontent.com/29389746/129096386-68c48933-b3d3-4260-be03-69d7948ae565.png)

This is where it is within the settings.

![126048068-74ff7f0c-9af0-425b-bbfb-7e213ad6c97d](https://user-images.githubusercontent.com/29389746/129096417-bae5192c-62cf-4d6f-9970-fe32f4fd10fb.png)

![126048070-8fe7f822-d9ce-4452-9943-2a0e46ac73f0](https://user-images.githubusercontent.com/29389746/129096439-e3b82a06-a15d-4272-ae47-5ec6cccc9f13.png)

But wondering if its simple enough to take the code from Arctic Horizon and just throw it in this skin as well?

**Comment by nfm886** [comment]
> But wondering if its simple enough to take the code from Arctic Horizon and just throw it in this skin as well?
Not really... Cosmic is based on Estuary. Code is completely different from what jurialmunkey's did.
However, I will consider to adding this view. Eventually it will happen in the near future, since there is a lot of other places to improve.

**Comment by icpryde** [comment]
Ok no problem 👍🏽 Thanks for the hard work you are doing

**Comment by nfm886** [comment]
Closing for now. You will know when I add something similar to this view.
